### ISSUE TITLE
Approaches to themes in A3 and Vue

### ISSUE THREAD

**Issue by austinstarin** [apostrophecms/apostrophe-storybook#31]
Here are my initial notes and pseudo code exploring possible ways to handle theming in Vue/A3. I think there are two questions that came up and solidified as I looked into this further:

- Should we allow for only light/dark mode theming?
- Is project level theming a real need and feature?

I've been thinking on this Harry Robert's quote:
>Theming, the vast majority of the time, is a complete nice-to-have. It is not business critical or usually even important. If you are asked to provide such theming, do not do so at the expense of performance or code quality.

### Pros
* Dynamic styling
* Possible for central theme config in js at app root or server app root

### Cons
* More complex architecture/code (CSS in JS)
* Library is a React library ported for Vue and is not feature rich

### Example

In single-file component:
```js
import styled from 'vue-styled-components';

// btnProps could be referenced in bus or app config
const btnProps = { theme: String };

const StyledButton = styled('button',  btnProps)`
  color: ${props => props.theme};
`;

export default StyledButton;
```

### Pros
* Theme specific modifier classes are not bundled for the application reducing the amount of unused CSS in the bundle

### Cons
*  Additional Webpack loader dependency. Loader has ~80 weekly downloads, and I don't see referenced as a best practice anywhere.
* More complex architecture/code

### Example
An example of the Webpack configuration would look like:
```
module.exports = {
  module: {
    rules: [
     {
        test: /\.vue$/,
        use: [
          {
            loader: 'vue-loader'
          },
          { 
            loader: 'vue-theme-loader',
            options: {
              theme: 'primary'
            }
          }
        ]
      }
    ]
  }
}
```
Every single file component for the application would have a non-themed block and as many theme specific blocks as needed:
```css

<style>
  .button {
    padding: 0;
  }
</style>
 
<style theme="primary">
  .button {
    color: red;
  }
</style>
 
<style theme="secondary">
  .button {
    color: blue;
  }
</style>
```

### Pros
* There are no additional dependencies needed to achieve themes(s)
* Less complex architecture/code

### Cons
* Unused theme(s) code is bundled/pushed
* Does not allow for dynamic styling
* Does not allow for custom theme configuration

### Example
```css
<style>
  .button {
    padding: 0;
  }

  .button--primary {
    color: red;
  }

  .button--secondary {
    color: blue
  }
</style>
```

## 4. Use a custom Webpack loader to extract and compile a configurable Sass map that applies a theme. Maybe the map is configured in project level code and abstracted and built?

This is half-baked at the moment and was part of a conversation I had with @bgantick, but seems like a possible solution with further technical validation.

### Pros
* Less complex/architecture code at component level

### Cons
* More complex architecture/code
* We need to author a Wepback loader to handle this use case

```css
<style>
  .button {
    color($map, 'shade-two');
  }
</style>
```
